platform :ios, '7.0'
pod 'ECSlidingViewController', '~> 2.0.2'
pod 'Parse'
pod 'Shimmer'
pod 'SDWebImage', '~> 3.6'
pod 'MDCSwipeToChoose'
pod 'SVProgressHUD', :head
pod 'HTAutocompleteTextField'
pod 'DZNPhotoPickerController', '~> 1.0.7'
pod 'pop', '~> 1.0'
pod 'DBCamera', '~> 2.3'
pod 'DWTagList', '~> 0.0.5'
pod 'OCMapView'